on:
  push:
    branches:
      - master

  schedule:
    - cron: '0 0 * * *' # Once per day at midnight

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies and run script
        run: |
          pip install -r requirements.txt -q
          python main.py
      - uses: stefanzweifel/git-auto-commit-action@v4.1.3
        with:
          commit_message: Update out.ics
          file_pattern: out.ics
          commit_user_name: GitHub Actions
